name = "blog"

account_id = ""
workers_dev = true
main = "./build/index.js"
compatibility_date = "2022-05-13"

[site]
bucket = "./public"

[build]
command = "npm run build"

[[r2_buckets]]
binding = 'BLOG_POSTS'
bucket_name = 'blog-posts'
